sudo: false

language: python

python:
  - "2.7"
  - "3.6"

branches:
  except:
    - ConjugateEverything
    - ConjugateEverythingPages

env:
  - CONDA=true

install:
  - lsb_release -a
  - source auto_version/travis_install_conda.sh numpy scipy numba pip pytest mpmath sympy
  - pip install packaging
  - conda install -c moble quaternion spinsfast
  - python setup.py install

# before_script:
#   - rvm get stable # https://github.com/travis-ci/travis-ci/issues/6307

script:
  # I've had to make some tests' accuracy depend on the value of
  # ell_max, so I run the tests for multiple values of ell_max -- in
  # particular, for my most important use case, ell=8.  And then I run
  # again for the largest ell_max, but only the faster tests, so that
  # Travis isn't overtaxed.  (Those slower tests have already
  # established their patterns anyway; the interesting tests for large
  # ell_max are the ones like overflow and underflow, which are pretty
  # fast anyway.)
  # - py.test test_* --cov=spherical_functions --ell_max 8 --run_slow_tests -s
  - py.test --ell_max 8 --run_slow_tests -s
  - py.test --ell_max 32 -s

# after_success:
#   coveralls

after_success:
  # Change permissions for Anaconda deployment script
  - chmod +x ./.conda_deploy.sh
  - python ./.meta_yaml_replacer.py

deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: "./.conda_deploy.sh"
    skip_cleanup: true
  - provider: pypi
    user: moboyle79
    password:
      secure: Dksv2EeU1Kgavi9aTKabbojuAaY3ZWscX4PLSF2HfISpdwfq6uTbyJr/UO584/1NMmPUslIFHY+PU47+klizYSMqsRYSLnBXnRITxWym9RDsW3bhZq4rUCik6P35fQsCeNdJ6idWwAyR2B3PGbEbmuIxJ5zvnFYJnlwinFqgmKc=
    on:
      distributions: sdist bdist_wheel
      repo: moble/spherical_functions
      python: '3.6'
      condition: $CONDA = 'true'

after_script:
  # if we do not unset this before we terminate the travis teardown will mark the entire job as failed
  - set +e
