defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude: [serve.sh]
markdown:    kramdown
kramdown:
  input: GFM
  hard_wrap: false
